### ISSUE TITLE
Naming is hard, we have the wrong names

### ISSUE THREAD

**Issue by rjw57** [cuspaceflight/firefish#21]
I named this repo m3cfd and almost immediately that name became wrong when we wanted to have a solution which was not necessarily Martlet 3 specific but be helpful generally.

Then the fin flutter stuff was added and the "cfd" part of the name became wrong.

Now we have a Python module with the bland name "cusfsim" which was intended to evoke the module containing CUSF simulation code but that's wrong since only *some* simulation code lives here.

Now we're in the situation where we have a repo with an incorrect name hosting a Python library with a *different* and (IMHO) overly generic name.

Really what we should've done is come up with a semantically neutral name like https://github.com/rjw57/aonui or https://github.com/cuspaceflight/tawhiri.

So my question is: are people on board with renaming things? It'd be a wee bit annoying since there'll have to be a flag day when people stop writing code with the old name and start with the new. It'd probably be best to do it during a project meeting.

Opinions?

**Comment by rjw57** [comment]
Pinging @jb803, @boyuanxiao and @JMW95 as people who've forked the repo so far.

**Comment by rjw57** [comment]
Anyone who's wondering what the name should be might have a merry few minutes clicking the button on http://mrsharpoblunto.github.io/foswig.js/.

**Comment by rjw57** [comment]
Maybe also take a look at https://en.wikipedia.org/wiki/List_of_common_fish_names if we want to retain some notion of "fluids" :).

**Comment by RedGhostMe** [comment]
Web Telegram
I do not know where to write.
In general, I have found a mistake in the emoji table
\xF0\x9F\x93\xA2 <=> \xF0\x9F\x93\xA3
public address loudspeaker <=> cheering megaphone
Thanks!

**Comment by jb803** [comment]
Fish names are a good idea. I quite like 'Guppy' (partly because it sounds nice and because it reminds me of: https://en.wikipedia.org/wiki/Aero_Spacelines_Super_Guppy )

**Comment by JDavidson94** [comment]
Guppy is a good shout.

**Comment by rjw57** [comment]
:+1: for guppy

**Comment by rjw57** [comment]
(Although there's already a PyPI for guppy: https://pypi.python.org/pypi/guppy)

**Comment by rjw57** [comment]
OK, at the meeting we've decided on "firefish".
